#!/usr/bin/env bash
# Bash script that will display information about subdomains.

web_info () {
  printf "The subdomain %s is a " "$2"
  dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $4 }'
  printf " record and points to "
  dig "$2.$1" | grep -A1 'ANSWER SECTION:' | awk -F' ' '{ printf $5 }'
  echo ""
}

if [ -z "$2" ]; then
  for sub_domain in "www" "lb-01" "web-01" "web-02"
  do
    web_info "$1" "$sub_domain"
  done
else
  web_info "$1" "$2"
fi
