#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

error="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"

if [[ $# -lt 3 ]]; then
  echo "$error"
elif [[ "$#" -lt 4 ]]; then
  scp -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
else
  scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3"@"$2":~/
fi
