#!/usr/bin/env bash
# Configure a running Ngix and installation from listening on port 80

# Remove the default configuration
rm -f /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sed -i 's/listen 8080/listen 80/g' /etc/nginx/sites-enabled/default
service nginx restart
