#!/usr/bin/env bash
# Bash script to configure Nginx to install, run and listen on port 80
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
pkill -f --signal 1 "/usr/sbin/nginx"
service nginx start
