#!/usr/bin/env bash
# a Bash script that displays the content of the file /etc/passwd.
#  Only displays the username, user id, and user home directory path.

while IFS= read -r passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
