#!/usr/bin/env bash
# A script that prints the word 'Best School' but on the 9th ieration, prints 'Hi' afterwards

count="0"

while [ "$count" -lt 11 ];
do
	echo "Best School"
	if [ "$count" -eq 9 ]
	then
        	echo "Hi"
	fi
	count=$(( count += 1 ))
done
