#!/usr/bin/env bash
# A script that prints the word 'Best School' but on the 9th ieration, prints 'Hi' afterwards

c="0"

while [ "$c" -lt 10 ];
do
	echo "Best School"
	((c++))
	if [ "$c" -eq 9 ]
	then
        	echo "Hi"
	fi
done
