#!/usr/bin/env bash
# Write a Bash script that displays the time for 12 hours and 59 minutes:

h=0
while [ "$h" -le 12 ];
do
	echo "Hour: $h"
	m=0
	while [ "$m" -lt 60 ];
	do
		echo "$m"
		((m++))
	done
	((h++))
done
